STANDARD_BUFFER_SIZE = 1024
NUMBER_OF_PACKET_LENGTH_BYTE = 8
NUMBER_OF_PACKET_TYPE_BYTE = 1
PACKET_LENGTH_FORMAT = ">Q"
PACKET_TYPE_FORMAT = ">B"
DEFAULT_ADDRESS = ("127.0.0.1", 8080)

CLIENT_HELLO_MSG = b"CLIENT HELLO"
SERVER_WELCOME_MSG = b"SERVER WELCOME"
REQUEST_MODEL_MSG = b"REQ MODEL"
